### ISSUE TITLE
Usage in Rancher

### ISSUE THREAD

**Issue by phal0r** [Negashev/hade#1]
Hi @Negashev ,

thanks for this project. Comes in really handy for me, but I recognized some mistakes in the Readme, if one wants to use this with Rancher.

- underscores are not allowed in Rancher -> instead of `haproxy_exporter` use `haproxy-exporter`
- volumes_from in Rancher makes only sense, when haproxy-exporter is used as a sidekick
- the haproxy url should not contain a `?` but instead the url should be `http://https.lb.rancher.internal:9000/stats;csv` (it looks strange, but this is the way haproxy provides stats information as csv :D)

**Comment by Negashev** [comment]
@phal0r Thanks for the comments,  here's a working version with my rancher 1.6.12

```yaml
version: '2'
services:
 hade:
    image: negash/hade
    environment:
      RESOLVE_TYPE: rancher
      DOMAIN: http://web.lb.rancher.internal:9999/?stats;csv
    tty: true
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1mb
    volumes_from:
    - haproxy-exporter
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: haproxy-exporter
  haproxy-exporter:
    image: quay.io/prometheus/haproxy-exporter
    entrypoint:
    - /bin/sh
    stdin_open: true
    volumes:
    - /exec
    tty: true
    command:
    - -c
    - cp /bin/haproxy_exporter /exec/haproxy_exporter
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.pull_image: always
```
